import Head from 'next/head';
import { Lato } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { getOptionsForVote } from '@/utils/getRandomPokemon';
import { trpc } from '@/utils/trpc';
import { FC, useState } from 'react';
import Image from 'next/image';

const lato = Lato({ subsets: ['latin'], weight: '400' });

interface HomeProps {
  first: number;
  second: number;
}

export const Home: FC<HomeProps> = () => {
  const [ids, setIds] = useState(() => getOptionsForVote());

  const firstPokemon = trpc.getPokemonById.useQuery({ id: ids[0] });
  const secondPokemon = trpc.getPokemonById.useQuery({ id: ids[1] });

  if (!firstPokemon.data || !secondPokemon.data) {
    return <div>Loading...</div>;
  }

  const voteForPokemon = (selected: number) => {
    // todo: fire mutation to persist changes

    setIds(getOptionsForVote());
  };

  const handleImageClick = () => {
    alert('TODO: onClick handler');
  };

  return (
    <>
      <Head>
        <title>Which Pokemon is Most Round</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${lato.className}`}>
        <h1>Which Pokemon is Most Round?</h1>
        <div className={styles.voting_section}>
          <div className={styles.vote_container}>
            <Image
              src={firstPokemon.data.sprites.front_default ?? ''}
              alt="poke"
              width={100}
              height={100}
              onClick={handleImageClick}
            />
            <p className={styles.poke_name}>{firstPokemon.data.name}</p>
            <button
              className={styles.btn}
              onClick={() => voteForPokemon(1)}
            >
              Vote
            </button>
          </div>
          <div className={styles.vote_tag}>Vs</div>
          <div className={styles.vote_container}>
            <Image
              src={secondPokemon.data.sprites.front_default ?? ''}
              alt="poke"
              width={100}
              height={100}
              onClick={handleImageClick}
            />
            <p className={styles.poke_name}>{secondPokemon.data.name}</p>
            <button
              className={styles.btn}
              onClick={() => voteForPokemon(1)}
            >
              Vote
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
